version: '3'
services:

  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    image: fcontrol-api
    container_name: fcontrol-api-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - api

  mysql:
    image: mysql:8.0
    container_name: fcontrol-api-db
    ports:
      - '3309:3306'
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './docker/mysql/data:/var/lib/mysql'
    networks:
      - api

  nginx:
    image: nginx:alpine
    container_name: fcontrol-api-nginx
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - api

networks:
  api:
    driver: bridge

